name: Melon Ticket Checker
on:
  schedule:
    - cron: '*/5 * * * *'   # 5분마다 실행
  workflow_dispatch:        # 필요 시 수동 실행
jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check Tickets
        uses: mooyoul/melon-ticket-actions@v1.1.0
        with:
          product-id: 211942
          schedule-id: 100334
          seat-id: 1_0
          slack-incoming-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: '<@UXXXXXXX> 10/24 오픈 감지!'
